name: "ffmpeg"
on: 
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        sudo apt-get update
        sudo apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
        sudo apt-get install -yqq wget aria2 ffmpeg telnet tree lshw
        aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://onejav.com/torrent/snkh004/download/172659/onejav.com_snkh004.torrent"
        ls -hal
    - name: "Deploy dropbox"
      uses: aTable/deploy-to-dropbox@e1d6400acb642bc7f4f14e5eb83cad4bec5b304b
      with:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        DROPBOX_DESTINATION_PATH_PREFIX: "/"
        GLOB: "SNKH-004.mp4"
        DEBUG: false